In [16]:
import pandas as pd
import numpy as np
import re

In [17]:
df=pd.read_csv("C:\\Users\\vaish\\OneDrive\\Documents\\Online_Books_Price_&_Rating_Analysis\\Books_Scraped_dataset.csv")

In [18]:
df

,title,rating_tag,price_tag,availible_tag,category
0,A Light in the ...,Three,Â£51.77,In stock,Poetry
1,Tipping the Velvet,One,Â£53.74,In stock,Historical Fiction
2,Soumission,One,Â£50.10,In stock,Fiction
3,Sharp Objects,Four,Â£47.82,In stock,Mystery
4,Sapiens: A Brief History ...,Five,Â£54.23,In stock,History
...,...,...,...,...,...
575,Our Band Could Be ...,Three,Â£57.25,In stock,Music
576,Olio,One,Â£23.88,In stock,Poetry
577,Mesaerion: The Best Science ...,One,Â£37.59,In stock,Science Fiction
578,Libertarianism for Beginners,Two,Â£51.33,In stock,Politics
579,It's Only the Himalayas,Two,Â£45.17,In stock,Travel

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 580 entries, 0 to 579
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          580 non-null    str
 1   rating_tag     580 non-null    str
 2   price_tag      580 non-null    str
 3   availible_tag  580 non-null    str
 4   category       580 non-null    str
dtypes: str(5)
memory usage: 22.8 KB

In [20]:
df.duplicated().sum()

np.int64(560)

In [21]:
df.isnull().sum()

title            0
rating_tag       0
price_tag        0
availible_tag    0
category         0
dtype: int64

In [22]:
# changing names for easier understanding

df.columns=df.columns.str.strip().str.replace({
    'price_tag':'price',
    'availible_tag':'avalibility',
    'category_tag':'category',
    'rating_tag':'rating'
})

In [23]:
# replacing the categorical data into numerical

df['rating']=df['rating'].str.replace({
    "One":"1",
    "Two":'2',
    "Three":'3',
    "Four":'4',
    "Five":'5'
})

In [24]:
# converting the rating into numrerical 

df['rating']=pd.to_numeric(df['rating'],errors="coerce")

In [25]:
# standardise the category column

df['category']=df['category'].str.strip().str.title()

In [26]:
# drop the duplicates in title column

# df['title']=df['title'].drop_duplicates()

In [27]:
# handeling the avalibility column by removing the extra spaces

df['avalibility'].str.strip()

0      In stock
1      In stock
2      In stock
3      In stock
4      In stock
         ...
575    In stock
576    In stock
577    In stock
578    In stock
579    In stock
Name: avalibility, Length: 580, dtype: str

In [28]:
# convetring the colun into str to perform replacing
df['price']=df['price'].astype(str)

# removing the symb
df['price']=df['price'].str.replace("Â£",'',regex=False).astype(float)

df['price'] = pd.to_numeric(df['price'].astype(str).str.replace("Â£", "", regex=False), errors='coerce').fillna(0)

In [29]:
df

,title,rating,price,avalibility,category
0,A Light in the ...,3,51.77,In stock,Poetry
1,Tipping the Velvet,1,53.74,In stock,Historical Fiction
2,Soumission,1,50.10,In stock,Fiction
3,Sharp Objects,4,47.82,In stock,Mystery
4,Sapiens: A Brief History ...,5,54.23,In stock,History
...,...,...,...,...,...
575,Our Band Could Be ...,3,57.25,In stock,Music
576,Olio,1,23.88,In stock,Poetry
577,Mesaerion: The Best Science ...,1,37.59,In stock,Science Fiction
578,Libertarianism for Beginners,2,51.33,In stock,Politics
579,It's Only the Himalayas,2,45.17,In stock,Travel

In [30]:
df.to_csv("Cleaned_Books_excel.csv")